#!/bin/csh
#
#   Script to Run PMCAMx for eastern US July 12-28, 2001 test case
#
set INPUT  = "/home/kwagstro/CAMx4inputs"
set INPUTA = "/home/kwagstro/CAMx4inputs/prep/area"
set INPUTP = "/home/kwagstro/CAMx4inputs/prep/point"

set DATE    = $1
set DATE2   = $2
@ DATE3   = $DATE - 1
#
set RUN     = "PIT1"
set OUTPUT  = "/home/kwagstro/PMCAMx4output/$RUN"
#
if ($DATE == "193") then
  mkdir -p $OUTPUT
  set RST  = "false"
  set RSTF = ""
else
  set RST  = "true"
  set RSTF = $OUTPUT/4rpos.$DATE3.$RUN.inst.2
endif 
echo $OUTPUT/4rpos.$DATE3.$RUN.inst.2
#
date 
#
#  --- Create the input file (always called CAMx.in)
#
cat << ieof > CAMx.in
CAMx Version       |VERSION4.0
Run Message        |PMCAMx v4.0 eastern US PM Test Run July 12-28 2001
Root output name   |$OUTPUT/4rpos.$DATE.$RUN
Start yr/mo/dy/hr  |01 07 $DATE2 0000.
End   yr/mo/dy/hr  |01 07 $DATE2 2400.
DT:max,met,ems,out |15. 60. 60. 60.
nx,ny,nz           |97   90   14
sCoordinate ID     |LAMBERT
xorg,yorg,dx,dy    |-900. -1620.  36.  36. -97 40 33 45
time zone          |5
PiG parameters     |2000. 12.
Avg output species |169
                   |NO        NO2       O3        PAR       TOL       CO
                   |OLE       PAN       OLE2      XYL       FORM      ALD2
                   |HNO3      NXOY      NTR       HONO      H2O2      MEOH
                   |ETOH      CRES      CG1       CG2       CG3       CG4
                   |SO2       NH3       HCL       SULF      KW        SOA1_1    
                   |SOA1_2    SOA1_3    SOA1_4    SOA1_5    SOA1_6    SOA1_7    
                   |SOA1_8    SOA1_9    SOA1_10   SOA2_1    SOA2_2    SOA2_3    
                   |SOA2_4    SOA2_5    SOA2_6    SOA2_7    SOA2_8    SOA2_9    
                   |SOA2_10   SOA3_1    SOA3_2    SOA3_3    SOA3_4    SOA3_5    
                   |SOA3_6    SOA3_7    SOA3_8    SOA3_9    SOA3_10   SOA4_1    
                   |SOA4_2    SOA4_3    SOA4_4    SOA4_5    SOA4_6    SOA4_7    
                   |SOA4_8    SOA4_9    SOA4_10   POC_1     POC_2     POC_3     
                   |POC_4     POC_5     POC_6     POC_7     POC_8     POC_9    
                   |POC_10    PEC_1     PEC_2     PEC_3     PEC_4     PEC_5     
                   |PEC_6     PEC_7     PEC_8     PEC_9     PEC_10    CRST_1    
                   |CRST_2    CRST_3    CRST_4    CRST_5    CRST_6    CRST_7    
                   |CRST_8    CRST_9    CRST_10   PH2O_1    PH2O_2    PH2O_3    
                   |PH2O_4    PH2O_5    PH2O_6    PH2O_7    PH2O_8    PH2O_9    
                   |PH2O_10   PCL_1     PCL_2     PCL_3     PCL_4     PCL_5     
                   |PCL_6     PCL_7     PCL_8     PCL_9     PCL_10    NA_1      
                   |NA_2      NA_3      NA_4      NA_5      NA_6      NA_7      
                   |NA_8      NA_9      NA_10     PNH4_1    PNH4_2    PNH4_3    
                   |PNH4_4    PNH4_5    PNH4_6    PNH4_7    PNH4_8    PNH4_9    
                   |PNH4_10   PNO3_1    PNO3_2    PNO3_3    PNO3_4    PNO3_5    
                   |PNO3_6    PNO3_7    PNO3_8    PNO3_9    PNO3_10   PSO4_1    
                   |PSO4_2    PSO4_3    PSO4_4    PSO4_5    PSO4_6    PSO4_7    
                   |PSO4_8    PSO4_9    PSO4_10   PKW_1     PKW_2     PKW_3
                   |PKW_4     PKW_5     PKW_6     PKW_7     PKW_8     PKW_9
                   |PKW_10
# nested grids     |0
SMOLAR,BOTT, PPM?  |PPM
Chemistry solver   |CMC
Restart            |$RST
Chemistry          |true
Dry dep            |true
Wet dep            |true
PiG submodel       |false
Staggered winds    |false
Treat area emiss   |true
Treat point emiss  |true
1-day emiss inputs |true
3-D average file   |false
Probing tools      |false
Chemparam          |$INPUT/init/CAMx4.chemparam.6.SO2H2SO4
Photolysis rates   |$INPUT/rate/rate.2001$DATE.do.mech3
Landuse            |$INPUT/init/surf.4rpos.36.ld.bin
Height/pressure    |$INPUT/pres/pres.2001$DATE.4rpos.36.14.mm5.ld.camx
Wind               |$INPUT/wind/wind.2001$DATE.4rpos.36.14.mm5.ld.camx
Temperature        |$INPUT/temp/temp.2001$DATE.4rpos.36.14.mm5.ld.camx
Water vapor        |$INPUT/wvap/wvap.2001$DATE.4rpos.36.14.mm5.ld.camx
Cloud/rain         |$INPUT/clranew/clra.2001$DATE.4rpos.36.14.mm5.ld.camx
Vertical diffsvty  |$INPUT/vdif/vdif.2001$DATE.4rpos.36.14.mm5.ld.camx.PATCH
Initial conditions |$INPUT/init/init.2001.4rpos.36.14.m3profile.ld.camx
Boundary conditions|$INPUT/init/bndr.2001.4rpos.36.14.m3profile.ld.camx
Top concentration  |$INPUT/init/topc.2001.4rpos.36.14.m3profile.ld.camx
Albedo/haze/ozone  |$INPUT/ahoz/ahoz.2001$DATE.4rpos.36.ld
Point emiss        |$INPUTP/ptsr.2001$DATE.4rpos.NR.baseE.ld.camx
Area emiss         |$INPUTA/lamb.2001$DATE.4rpos.36.baseE.ld.camx
Restart file name  |$RSTF
ieof
#
#  --- Execute the model ---
#
/usr/bin/time /home/kwagstro/DevApp/Loc2/CAMx.ladco.linux.PIT1
date 
#
